FROM node

# Labels
LABEL maintainer="Alexsouye, <buissonalexandre16@gmail.com>"
LABEL version="2.0.1"

# Set environment variables
ENV TOKEN=
ENV PORT=8080

# Reserve ports
EXPOSE 8080

# Create app directory
WORKDIR /usr/src/app

# Move all files
COPY . /usr/src/app/

# RUN npm install
RUN npm install

# Build project
RUN npm run build

# Start bot
CMD [ "node", "build/client.js" ]